		<div class="footer">
            <p>Les concepteurs du jeu&nbsp;:
                <a href="http://www.lirmm.fr/~lafourcade/index2.html">Mathieu LAFOURCADE</a> et
                <a href="http://w3.u-grenoble3.fr/zampa/index.html">Virginie ZAMPA</a> - 
                <a href="http://www.lirmm.fr/pticlic/pticlic.php?about=1">L'histoire du PtiClic</a> - 
                <a href="http://www.lirmm.fr/pticlic/pticlic.php">Jouer au PtiClic sur un ordinateur</a> - 
                <a href="http://www.lirmm.fr/jeuxdemots/jdm-accueil.php">Jeux de mots</a> - 
                <a href="http://www.univ-montp2.fr/">Université Montpellier II</a> - 
                <a href="http://www.lirmm.fr/">Laboratoire d'Informatique, de Robotique et de Microélectronique de Montpellier</a> - 
                <a href="contact.php">Nous contacter</a> -
                Android is a trademark of Google Inc. Use of this trademark is subject to
                <a href="http://www.google.com/permissions/index.html"> Google Permissions</a>
            </p>
		</div>